Add ovpn_addstaticip command.

diff --git a/bin/dockervpn b/bin/dockervpn
--- a/bin/dockervpn
+++ b/bin/dockervpn
@@ -13,7 +13,7 @@ The list of commands is:
 
     backup       - backup up the /etc/openvpn directory to a tar file
     bash         - enter a bash shell in the container
-    install      - install and run docker container
+    install      - install and optionally run docker container
     getclient    - retrieve a client configuration file
     listclients  - display a list of configured clients
     listcustom   - display a list of custom file fragments
@@ -81,13 +81,17 @@ cmd_help() {
         "
         ;;
         install) echo "
-    install domain_name [vpn_port]
-        Install and run the docker container - domain_name is required, vpn_port is optional. The
-        container will be configured for vpn.domain_name so dns should resolve that name to the 
-        correct vpn server address. The container will also be configured to listen on udp port 
-        vpn_port (defaults to 1194). This dockervpn script will also be copied to /usr/local/bin.
-        The docker container will be started with restart unless_stopped, so the vpn server should
-        restart on host reboots unless it is stopped before the reboot.
+    install -d domain_name [-p port] [-c] [-s data_directory]
+        Install and optionally run the docker container - -d domain_name is required, -p, -s, and -c are 
+        optional. The container will be configured for vpn.domain_name so dns should resolve that 
+        name to the correct vpn server address. The container will also be configured to listen on 
+        the specified udp port (defaults to 1194) if the -p option is included. The container will
+        be configured but not run if the -c option is included. This allows the container to be 
+        configured but run with a different method such as with docker-compose. The data directory for
+        the container will be located at data_directory (defaults to /srv/docker-openvpn/data) if the 
+        -s option is included. This dockervpn script will also be copied to /usr/local/bin. If the 
+        docker container is run, then it will be started with restart unless_stopped, so the vpn server 
+        should restart on host reboots unless it is stopped before the reboot.
         "
         ;;
         listclients) echo "
@@ -185,24 +189,58 @@ getclient() {
 }
 
 install() {
-    if [ -z "$1" ]; then
+    install_run=1
+    install_port=1194
+
+    while getopts ":d:p:s:c" install_opt; do
+        case $install_opt in
+            p)
+                install_port="$OPTARG"
+                ;;
+            d)
+                install_domain_name="$OPTARG"
+                ;;
+            c)
+                install_run=0
+                ;;
+            s)
+                install_srv_dir="$OPTARG"
+                ;;
+            \?)
+                set +x
+                >&2 echo "Invalid option: -$OPTARG"
+                >&2 cmd_help install
+                exit 1
+                ;;
+            :)
+                set +x
+                >&2 echo "Option -$OPTARG requires an argument."
+                >&2 cmd_help install
+                exit 1
+                ;;
+        esac
+    done
+
+    if [ -z "$install_domain_name" ]; then
         >&2 echo "Domain name is required.\n"
         >&2 cmd_help install
         exit 1
     fi
-    if [ -z "$2" ]; then
-        OPENVPN_PORT_NUMBER=1194
-    else
-        OPENVPN_PORT_NUMBER=$2
+    if [ -z "$install_srv_dir" ]; then
+        install_srv_dir="/srv/docker-openvpn/data"
     fi
+
     cp $0 /usr/local/bin/dockervpn
-    docker run -v openvpn_data:/etc/openvpn --rm -it castone38/dockervpn ovpn_genconfig \
-        -u udp://vpn.$1 -C AES-256-GCM -c -a SHA256 -s "10.8.0.0/24" -d \
-        -n "208.67.222.222 208.67.220.220" -e "explicit-exit-notify 1" \
+    mkdir -p $install_srv_dir
+    docker run -v $install_srv_dir:/etc/openvpn --rm -it castone38/dockervpn ovpn_genconfig \
+        -u udp://vpn.$install_domain_name:$install_port -C AES-256-GCM -c -a SHA256 \
+        -s "10.8.0.0/24" -d -n "208.67.222.222 208.67.220.220" -e "explicit-exit-notify 1" \
         -e "ifconfig-pool-persist /etc/openvpn/ipp.txt" \
         -p "redirect-gateway def1 bypass-dhcp"
-    docker run --name openvpn --restart unless-stopped -v openvpn_data:/etc/openvpn -d \
-        -p $OPENVPN_PORT_NUMBER:1194/udp --cap-add=NET_ADMIN castone38/dockervpn
+    if [[ $install_run == 1 ]]; then
+        docker run --name openvpn --restart unless-stopped -v $install_srv_dir:/etc/openvpn -d \
+            -p $install_port:$install_port/udp --cap-add=NET_ADMIN castone38/dockervpn
+    fi
 }
 
 listclients() {
